USE [AraWaitlist]
GO

---TABLE DROPS----
DROP TABLE [dbo].[Patient]
DROP TABLE [dbo].[Surgeon]
DROP TABLE [dbo].[Refferer]

---CREATING PATIENT TABLE
CREATE TABLE Patient(
patientID int IDENTITY(1,1) PRIMARY KEY,
NHI VARCHAR(7) NOT NULL,
firstName VARCHAR(25) NOT NULL,
lastName VARCHAR(25) NOT NULL,
DOB DATE NOT NULL,
gender CHAR(15) NOT NULL
)


---CREATING SURGEON TABLE
CREATE TABLE Surgeon(
surgeonId INT PRIMARY KEY NOT NULL,
fName VARCHAR(25) NOT NULL,
lName VARCHAR(25) NOT NULL,
department VARCHAR(25) NOT NULL
)


---CREATING REFFERER TABLE
CREATE TABLE Refferer(
staffId INT PRIMARY KEY NOT NULL,
fName VARCHAR(25) NOT NULL,
lName VARCHAR(25) NOT NULL,
refferedFrom VARCHAR(25) NOT NULL
)


