USE [AraWaitlist]
GO

---TABLE DROPS----
DROP TABLE [dbo].[Patient]
DROP TABLE [dbo].[Surgeon]

---CREATING PATIENT TABLE
CREATE TABLE Patient(
NHI VARCHAR(7) PRIMARY KEY NOT NULL,
firstName VARCHAR(25) NOT NULL,
lastName VARCHAR(25) NOT NULL,
DOB DATE NOT NULL,
gender CHAR(15) NOT NULL
)
SELECT * FROM [dbo].[Patient]
GO

---CReATING SURGEON TABLE
CREATE TABLE Surgeon(
surgeonId INT PRIMARY KEY NOT NULL,
fName VARCHAR(25) NOT NULL,
lName VARCHAR(25) NOT NULL,
department VARCHAR(25) NOT NULL
)
SELECT * FROM [dbo].[Surgeon]
GO

---CREATING REFFERER TABLE
CREATE TABLE Refferer(
staffId INT PRIMARY KEY NOT NULL,
fName VARCHAR(25) NOT NULL,
lName VARCHAR(25) NOT NULL,
refferedFrom VARCHAR(25) NOT NULL
)
SELECT * FROM [dbo].[Refferer]
GO