USE [AraWaitlist]
GO

DROP TABLE [dbo].[Patient]

CREATE TABLE Patient(
NHI VARCHAR(7) PRIMARY KEY NOT NULL,
firstName VARCHAR(25) NOT NULL,
lastName VARCHAR(25) NOT NULL,
DOB DATE NOT NULL,
gender CHAR(15) NOT NULL
)


SELECT * FROM [dbo].[Patient]
GO